server:
  port: 9113
#服务名称
eureka:
#开启ip注册
  instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
#    服务地址
    serviceUrl:
      defaultZone: http://xuesemofa:wangzheshengcun@localhost:9111/eureka/
#      服务名称
spring:
  application:
    name: account

#    配置数据源
  datasource:
    url: jdbc:mysql://39.106.33.113:3306/cloud?useUnicode=true&characterEncoding=ISO-8859-1&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
      show-sql: true